codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 75..100
  round: down
  precision: 2

   status:
    project: yes
    patch:
      default:
        target: 80%              # specify the target "X%" coverage to hit
        threshold: 5%          # allowed to drop X% and still result in a "success" commit status

ignore:
  - "mocks"